<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Keys\public_key_user.pem" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Keys\public_key_user.pem" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="5.1.0" />
    <PackageReference Include="Orcamentaria.Lib.Application" Version="1.1.1" />
    <PackageReference Include="Orcamentaria.Lib.Domain" Version="9.0.5" />
    <PackageReference Include="Orcamentaria.Lib.Infrastructure" Version="4.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Orcamentaria.PersonService.Application\Orcamentaria.PersonService.Application.csproj" />
    <ProjectReference Include="..\Orcamentaria.PersonService.Infrastructure\Orcamentaria.PersonService.Infrastructure.csproj" />
  </ItemGroup>

</Project>
