<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.11" />
    <PackageReference Include="Orcamentaria.Lib.Domain" Version="10.1.1" />
    <PackageReference Include="RabbitMQ.Client" Version="7.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Orcamentaria.PersonService.Domain\Orcamentaria.PersonService.Domain.csproj" />
  </ItemGroup>

</Project>
