<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.11" />
    <PackageReference Include="MySql.EntityFrameworkCore" Version="9.0.9" />
    <PackageReference Include="Orcamentaria.Lib.Infrastructure" Version="5.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Orcamentaria.PersonService.Domain\Orcamentaria.PersonService.Domain.csproj" />
  </ItemGroup>

</Project>
