-- MySQL Script generated by MySQL Workbench
-- Fri May 23 18:05:55 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema person-db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema person-db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `person-db` DEFAULT CHARACTER SET utf8 ;
USE `person-db` ;

-- -----------------------------------------------------
-- Table `person-db`.`T_PERSON`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `person-db`.`T_PERSON` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(30) NOT NULL,
  `RG` VARCHAR(9) NULL,
  `CPF` VARCHAR(11) NULL,
  `CNPJ` VARCHAR(14) NULL,
  `TYPE` INT NOT NULL,
  `COMPANY_ID` INT NOT NULL,
  `ACTIVE` BIT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `person-db`.`T_ADDRESS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `person-db`.`T_ADDRESS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `STREET` VARCHAR(70) NOT NULL,
  `ZIPCODE` VARCHAR(8) NOT NULL,
  `NUMBER` VARCHAR(6) NULL,
  `COMPLEMENT` VARCHAR(45) NULL,
  `NEIHBORHOOD` VARCHAR(100) NOT NULL,
  `CITY` VARCHAR(100) NOT NULL,
  `STATE` VARCHAR(45) NOT NULL,
  `UF` VARCHAR(2) NOT NULL,
  `DEFAULT` BIT NULL,
  `PERSON_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_T_ADDRESS_T_PERSON_idx` (`PERSON_ID` ASC) VISIBLE,
  CONSTRAINT `fk_T_ADDRESS_T_PERSON`
    FOREIGN KEY (`PERSON_ID`)
    REFERENCES `person-db`.`T_PERSON` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `person-db`.`T_CONTACT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `person-db`.`T_CONTACT` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CONTACT` VARCHAR(150) NOT NULL,
  `TYPE` INT NOT NULL,
  `DEFAULT` BIT NULL,
  `PERSON_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_T_CONTACT_T_PERSON1_idx` (`PERSON_ID` ASC) VISIBLE,
  CONSTRAINT `fk_T_CONTACT_T_PERSON`
    FOREIGN KEY (`PERSON_ID`)
    REFERENCES `person-db`.`T_PERSON` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `person-db`.`T_EMPLOYEE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `person-db`.`T_EMPLOYEE` (
  `ID` INT NOT NULL,
  `POST` VARCHAR(60) NOT NULL,
  `ADMISSION_DATE` DATETIME NOT NULL,
  `VALUE_PER_DAY` REAL NOT NULL,
  INDEX `fk_T_EMPLOYEE_T_PERSON1_idx` (`ID` ASC) VISIBLE,
  CONSTRAINT `fk_T_EMPLOYEE_T_PERSON`
    FOREIGN KEY (`ID`)
    REFERENCES `person-db`.`T_PERSON` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
